query MultipleLevelAcademicCourses($academicLevelId: [Int!]) {
    MultipleLevelAcademicCourses(AcademicLevelId: $academicLevelId) {
        Id
        CreatedAt
        UpdatedAt
        DeletedAt
        AcademicLevelId
        Name
    }
}