mutation NewStudentTutor($tutorId : Int!) {
    NewStudentTutor(userId: $tutorId) {
        Id
        CreatedAt
        UpdatedAt
        DeletedAt
        Name
        FamilyName
        NickName
        Email
        Matricule
        Age
        BirthDate
        Sex
        Lang
        Status
        ProfileImageXid
        Description
        CoverText
        Profile
        ExperienceDetail
        AdditionalDescription
        AddOnTitle
    }
}
