mutation UpdAcademicCoursePreference($coursesPreferences: UserAcademicCoursePreferenceInput!)  {
    UpdAcademicCoursePreference(coursesPreferences: $coursesPreferences) {
        Id
        CreatedAt
        UpdatedAt
        DeletedAt
        UserId
        IsOnline
    }
}