mutation UpdStudentAcademicCoursesPreferenceByParent($coursesPreferences: UserAcademicCoursePreferenceInput! , $studentId: Int!)  {
    UpdStudentAcademicCoursesPreferenceByParent(
        coursesPreferences: $coursesPreferences
        studentId: $studentId
    )
}