mutation SetStudentAcademicLevelByParent($academicLevelId : Int! , $studentId: Int!) {
    SetStudentAcademicLevelByParent(
        AcademicLevelId: $academicLevelId ,
         studentId: $studentId)
}
