mutation NewStudentAcademicCoursesByParent($courses: [UserAcademicCourseInput]! ,$studentId: Int!)   {
    NewStudentAcademicCoursesByParent(
        courses: $courses,
        studentId: $studentId)
}